import LocalizedStrings from "react-native-localization";
export default localization = new LocalizedStrings({
    en: {
        searchProducts:"Search Products",
        recentSearch:'Recent searches',
        clearAll:'clear all',
        offers:"Offers",
        orange:"Orange",
        computer:"computer",
        electronics:"electronics",
        comunications:"comunications",
        welcome:'Welcome',
        myAccount:'My Account',
        newFeed:'New Feed',
        myWishList:'My WishList',
        returnPolicy:'Return Policy',
        loginSignup:'Log in / Sign up',
        logout:'logout',
        total:'total',
        completeYourOrder:'Complete your order',
        brand:'Brand:',
        productCode:'Product Code:',
        availability:'Availability:',
        color:'Color:',
        buyNow:'Buy Now',
        specifications:'Specifications',
        readMore:'Read more',
        description:'Description',
        writeReview:'Write Review',
        approximateStuff:'Approximate Stuff',
        seeAll:'See All',
        shopByCategory:'Shop By Category',
        bestProducts:'Best Products',
        addToCart:'Add to Cart',
        contactUs:'contact us',
        more:'More',
        communications:'Communications',
        thisIsCategoryPage:'this is Category Page.',
        login:'Log in',
        firstName:"First Name",
        secondName:"Second Name",
        phone:'phone',
        email:"E-mail",
        password:"Password",
        confirm_Password:"Confirm-Password",
        country:"country",
        city:'city',
        signup:'sign up',
        dontHaveAccount:'Don\'t have an account?',
        createNow:'Create now.',
        rememberMe:"Remember me",
        forgetPassword:'Forget Password?',
        continueWithFacebook:'Continue with facebook',
        continueWithGoogle:'Continue with Google +',
        newPassword:"New Password",
        orderHistory:'order History',
        SHIPMENTNO:'SHIPMENT NO.',
        ORDERDATE:'ORDER DATE',
        TRACKSHIPMENT:'TRACK SHIPMENT',
        inprocessing:'inprocessing',
        shipped:'shipped',
        delivered:'delivered',
        expectedDelivery:'Expected delivery',
        status:'status',
        viewOrderDetails:'View Order Details',
        editProfile:'Edit Profile',
        secondName:"Second Name",
        shareWithFriends:'Share with friends',
        compare:'Compare',
        
    },
    ar: {
        searchProducts:"Search Products",
        recentSearch:'Recent searches',
        clearAll:'clear all',
        offers:"Offers",
        orange:"Orange",
        computer:"computer",
        electronics:"electronics",
        comunications:"comunications",
        welcome:'Welcome',
        myAccount:'My Account',
        newFeed:'New Feed',
        myWishList:'My WishList',
        returnPolicy:'Return Policy',
        loginSignup:'Log in / Sign up',
        logout:'logout',
        total:'total',
        completeYourOrder:'Complete your order',
        brand:'Brand:',
        productCode:'Product Code:',
        availability:'Availability:',
        color:'Color:',
        buyNow:'Buy Now',
        specifications:'Specifications',
        readMore:'Read more',
        description:'Description',
        writeReview:'Write Review',
        approximateStuff:'Approximate Stuff',
        seeAll:'See All',
        shopByCategory:'Shop By Category',
        bestProducts:'Best Products',
        addToCart:'Add to Cart',
        contactUs:'contact us',
        more:'More',
        communications:'Communications',
        thisIsCategoryPage:'this is Category Page.',
        login:'Log in',
        firstName:"First Name",
        secondName:"Second Name",
        phone:'phone',
        email:"E-mail",
        password:"Password",
        confirm_Password:"Confirm-Password",
        country:"country",
        city:'city',
        signup:'sign up',
        dontHaveAccount:'Don\'t have an account?',
        createNow:'Create now.',
        rememberMe:"Remember me",
        forgetPassword:'Forget Password?',
        continueWithFacebook:'Continue with facebook',
        continueWithGoogle:'Continue with Google +',
        newPassword:"New Password",
        orderHistory:'order History',
        SHIPMENTNO:'SHIPMENT NO.',
        ORDERDATE:'ORDER DATE',
        TRACKSHIPMENT:'TRACK SHIPMENT',
        inprocessing:'inprocessing',
        shipped:'shipped',
        delivered:'delivered',
        expectedDelivery:'Expected delivery',
        status:'status',
        viewOrderDetails:'View Order Details',
        editProfile:'Edit Profile',
        secondName:"Second Name",
        shareWithFriends:'Share with friends',
        compare:'Compare',
        
    }
})
